services:
  catalogapielk:
    image: catalogapielk
    build:
      context: .
      dockerfile: CatalogApiELK/Dockerfile


  elasticsearch:
    image: elasticsearch:7.9.2
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
      image: kibana:7.9.2
      container_name: kibana
      environment:
        ELASTICSEARCH_URL: http://elasticsearch:9200
      ports:
        - 5601:5601
      networks:
        - elastic

volumes:
    esdata:
      driver: local

networks:
    elastic:
      driver: bridge